### PR TITLE
Fixing configuration setting name for jwt secret key

### PR DESCRIPTION
**Pull request by daninus14**

### CODE REVIEW

**Comment by alvarosanchez** [comment]
Thanks for the PR.

I think `conf` is indeed a mistake, but the `grails.` prefix certainly not. What led you to think the prefix needs to be removed?

**Comment by daninus14** [comment]
oh, my bad, you are right. I just based it on an issue I found online,
because my own code was not compiling, just fixed it again... you are good
that you caught it :)

**Comment by alvarosanchez** [comment]
No problem, that's what PR reviews are for. Thanks for your contribution!

**Comment by daninus14** [comment]
Thank you! I think this was my first open source contribution ever :)

**Comment by alvarosanchez** [comment]
Congrats, and keep going!

**Pull request merged**
