### PR TITLE
fix for Grails 4 / Spring Security 5 based Spring-Security-Core plugin

### PR DESCRIPTION
**Pull request by rvanderwerf**
Because of breaking changes this version can only work for Grails 4. (Like with Spring Security Core, UI, ACL, etc)

### CODE REVIEW

**Comment by rvanderwerf** [comment]
We'll need to wait for the next Grails 4 milestone or RC release do be able to deploy this - it only works with a snapshot of current code, and the tests rely on sdkman which can't handle that. Once the next Grails 4 release milestone or candidate is released, we can just update the Grails version in this plugin and it should be good to go.

**Comment by rvanderwerf** [comment]
also note datastore-rest-client 6.1.12 needs to be released, or forked to a 7.0.0 line for GORM before this can go as well.

**Comment by patrikeev** [comment]
When are you going to release this? waiting to upgrade to grails 4, but I'm using this plugin...

**Comment by rvanderwerf** [comment]
We are working on a way release datastore-rest-client 6.1.12 since it's on a snapshot at the moment. Hopefully this week!

**Comment by pmmakela** [comment]
Any news on the release date?

**Pull request merged**
