### PR TITLE
Add support for CAS authentication using OAuth flow

### PR DESCRIPTION
**Pull request by rbfinch**
Implements #47.  A CAS provider can be configured in `Config.groovy` like this:

```
grails {
	plugin {
		springsecurity {
			rest {
				oauth {
					cas {
						client = org.pac4j.cas.client.CasClient
						casLoginUrl = "https://mycasserver.example.com/cas/login"
					}
				}
			}
		}
	}
}
```

Currently, the Pac4J client properties that can be configured are hardwired in `RestOauthService`.  Perhaps, it would be better to specify a closure in the oauth provider config that would allow any client specific property to be set.

### CODE REVIEW

**Comment by alvarosanchez** [comment]
This is awesome! Thank you very much. I'm asking you few more details before this can be merged:

- Add yourself as contributor in `README.md` (in alphabetical order).
- Add some documentation on how to use it creating a new file in `src/docs/guide/oauth` and adding it to `/src/docs/guide/toc.yml`.

**Comment by alvarosanchez** [comment]
Any chance of completing the changes I requested?

**Comment by rbfinch** [comment]
Sorry I haven't had a chance to get back to this.  I've been busy with a few other projects.

I'll take a look today.

Thanks!

-- Bob

**Comment by rbfinch** [comment]
I've made the documentation changes

**Comment by alvarosanchez** [comment]
Merged, thank you very much!

**Comment by kastork** [comment]
Question about this...

Can the CAS interaction be the normal one, or does this require the CAS server to implement oath?  I know CAS has oauth capabilities, but my institution doesn't want to configure that capability for some reason..

So I'm looking for a way to initiate the standard CAS protocol and get a regular JWT in return.  It looks like such a situation can be arranged, but I'm not understanding the docs well enough to see how to do it.

**Comment by kastork** [comment]
@rbfinch 

So... it looks to me like indeed this requires you to hit an 'oauth' endpoint on the CAS server.   `RestOauthService` checks for CAS and then calls on `CasOAuthWrapperClient`, which definitely is looking for the CAS oauth URL.

That's assuming you use the oauth workflow and pac4j CAS.

So I'm still looking for a way to just do a regular redirect to CAS, validate the CAS token and then dispense the JWT.

I'm still playing with it, but it seems you could use `spring-security-cas` and after validating the token at `/j_spring_cas_security_check`, then somehow come back to the token generating URL `/api/login` and deliver a token.

**Comment by jeffbliss** [comment]
@rbfinch 

Did you ever solve being able to do a regular redirect to CAS?

**Comment by kastork** [comment]
@jeffbliss No.  But it is once again becoming an issue for me.

**Pull request merged**
