### PR TITLE
Fix alvarosanchez/grails-spring-security-rest#284

### PR DESCRIPTION
**Pull request by zeludo**
PR for issue #284

### CODE REVIEW

**Comment by r1secure** [comment]
It's really a critical vulnerability. My company is also concerned. Pease, could you look at this issue?

**Comment by alvarosanchez** [comment]
@r1secure see my last comment at #284

**Comment by grzegorm** [comment]
@r1secure +1. It is also really a critical vulnerability for project in my company. I will be very thankful if you could look at this pull request as fast as it is possible, maybe even today or tomorrow. :)

**Comment by zeludo** [comment]
@alvarosanchez is there anything I could do to help make my PR automatically merged ? My branch was created from _1.5.3_ tag (commit 271f89fb8bee805912a50e00a48b538840409b56), but I can commit directly on _develop_ and make another PR.
This vulnerability is huge and really make this plugin useless till it is'nt fixed. It also opens the way for another even more critical vulnerability that could lead to full server access.

**Comment by alvarosanchez** [comment]
@zeludo the service you changed is just a regular Grails service Spring bean, and it's very easy to replace it in your application with your own version, as a workaround.

**Comment by alvarosanchez** [comment]
Merged manually. Will become part of the upcoming 1.5.4 and 2.0.0.M3 versions.

**Comment by alvarosanchez** [comment]
Versions `1.5.4` and `2.0.0.BUILD-SNAPSHOTS` have been just published

**Pull request closed without merging**
