### PR TITLE
Added Handling for rest authentication events

### PR DESCRIPTION
**Pull request by Schlogen**
…ndards of the spring security core plugin as well as core spring security

### CODE REVIEW

**Comment by alvarosanchez** [comment]
This looks great, but it needs some documentation, doesn't it?

**Comment by Schlogen** [comment]
@alvarosanchez Yes it does - I wasn't sure if you were going to want it. Now that I know you do, I'll add it.

**Comment by alvarosanchez** [comment]
@Schlogen any chance of completing the changes I mentioned?

**Comment by Schlogen** [comment]
@alvarosanchez It's the same documentation as the spring security core plugin, with the addition of an event. Is it enough to link to the original docs and add in the documentation for the new event? Or do you want the docs copied?

**Comment by Schlogen** [comment]
@alvarosanchez Not sure how to update the gh-pages branch with the .gdoc files. Have a link that describes the process?

**Comment by Schlogen** [comment]
@alvarosanchez Docs done. Please review

**Comment by alvarosanchez** [comment]
@Schlogen merged. Thank you for your business!

**Pull request merged**
